name: ESLint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  run-eslint:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install the things
      run: npm install

    - name: Run ESLint
      run: npm run lint
